Categories:
  - Connectivity
  - Development
  - Navigation
  - Security
  - System
License: GPL-3.0-only
AuthorName: jqssun
SourceCode: https://github.com/jqssun/android-gps-setter
IssueTracker: https://github.com/jqssun/android-gps-setter/issues
Changelog: https://github.com/jqssun/android-gps-setter/releases
Donate: https://jqssun.github.io/donate/

AutoName: GPS Setter

RepoType: git
Repo: https://github.com/jqssun/android-gps-setter.git
Binaries: https://github.com/jqssun/android-gps-setter/releases/download/v%v/app-foss-arm64-v8a-release.apk

Builds:
  - versionName: 1.1.1
    versionCode: 111
    commit: v1.1.1
    subdir: app
    gradle:
      - foss

AllowedAPKSigningKeys: F522AC71908397201DA222FF13CF587CA6E95B6F750EBCEFFD911B16F2B405C8

MaintainerNotes: scanner detects 'com/google/android/gms/...' from 'org.microg.gms:play-services-location`

AutoUpdateMode: Version
UpdateCheckMode: Tags
CurrentVersion: 1.1.1
CurrentVersionCode: 111
