# https://github.com/marketplace/actions/automated-build-android-app-with-github-action

name: Generate APK
env:
  main_project_module: app
on:
  push:
    branches:
      - 'release/**'
    tags:
      - 'v*.**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set current date as env variable
        run: echo "date_today=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Set repository name as env variable
        run: echo "repository_name=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV

      - name: Use JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21' # java version
          cache: 'gradle'

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Build debug
        run: ./gradlew assembleDebug

      - name: Upload debug apk (foss)
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.repository_name }} - ${{ env.date_today }}
          path: ${{ env.main_project_module }}/build/outputs/apk/foss/debug/

      - name: Upload debug apk (full)
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.repository_name }} - ${{ env.date_today }}
          path: ${{ env.main_project_module }}/build/outputs/apk/full/debug/
